# -*-coding:utf-8-*-
import time
from testCase.login.testLogin import Login
from testCase.base import Base


class NewProduct(Base):
    def __init__(self, cookie):
        self.page_url = '/products'
        super(NewProduct, self).__init__(cookie)

        # 普通产品的data
        self.ordinary_data = {
            'product[number]': 'CP' + time.strftime("%H:%M:%S"),
            'product[name]': '接口测试' + time.strftime("%H:%M:%S"),
            'product[barcode]': '条码' + time.strftime("%H:%M:%S"),
            'product[product_category_id]': '150530',
            'product[spec]': '规格',
            'product[note]': '产品备注',
            'product[unit_id]': '117200',
            'product[unit_name]': '包',
            'product[standard_price]': '1',
            'product[default_unit_id]': '117200',
            'product[default_in_unit_id]': '117200',
            'product[current_warning_policy]': 'no_warning',
            'product[split_warning_status]': 'split_closed',
            'product[total_warning_status]': 'total_closed',
            'product[attr_warning_status]': 'attr_warning_closed',
            'product[attr_status]': 'attr_closed',
            'product[price_policy_setting]': 'unit_policy',
            'product[unit_setting]': 'single_unit',
            'product[batch_status]': 'batch_closed',
            'product[serial_code_status]': 'serial_closed',
            'product[life_warning_days]': '',
            'product[life_period]': '',
            'product[use_purchase_attribute]': 'false',
            'product[use_sale_attribute]': 'false',
            'product[use_customer_setting]': 'false',
            'product[use_customer_price]': 'false',
            'product[product_units][0][unit_id]': '117200',
            'product[product_units][0][unit_name]': '包',
            'product[product_units][0][purchase_price_policies][0][unit_id]': '117200',
            'product[product_units][0][purchase_price_policies][0][unit_name]': '包',
            'product[product_units][0][purchase_price_policies][0][sale_price]': '',
            'product[product_units][0][purchase_price_policies][0][purchase_price]': '5',
            'product[product_units][0][purchase_price_policies][0][_destroy]': 'false',
            'product[product_units][0][sale_price_policies][0][unit_id]': '117200',
            'product[product_units][0][sale_price_policies][0][unit_name]': '包',
            'product[product_units][0][sale_price_policies][0][sale_price]': '8',
            'product[product_units][0][sale_price_policies][0][purchase_price]': '',
            'product[product_units][0][sale_price_policies][0][_destroy]': 'false',
            'product[product_customer_types][0][name]': '一级代理商',
            'product[product_customer_types][0][customer_type_id]': '107688',
            'product[product_customer_types][0][default_percentage]': '100.0',
            'product[product_customer_types][1][name]': '二级代理商',
            'product[product_customer_types][1][customer_type_id]': '107689',
            'product[product_customer_types][1][default_percentage]': '100.0',
            'product[product_customer_types][2][name]': '普通客户',
            'product[product_customer_types][2][customer_type_id]': '107690',
            'product[product_customer_types][2][default_percentage]': '100.0',
            'product[product_customer_types][3][name]': '大客户',
            'product[product_customer_types][3][customer_type_id]': '107691',
            'product[product_customer_types][3][default_percentage]': '100.0',
            'product[product_customer_types][4][name]': '批发客户',
            'product[product_customer_types][4][customer_type_id]': '107692',
            'product[product_customer_types][4][default_percentage]': '100.0',
            'product[text_field_74688f78d7]': '产品自定义字段供应商',
            'product[text_field_7776164791]': '产品自定义字段品质',
            'product[product_units_attributes][0][unit_id]': '117200',
            'product[product_units_attributes][0][unit_name]': '包',
            'product[product_units_attributes][0][price_policies_attributes][0][unit_id]': '117200',
            'product[product_units_attributes][0][price_policies_attributes][0][unit_name]': '包',
            'product[product_units_attributes][0][price_policies_attributes][0][sale_price]': '',
            'product[product_units_attributes][0][price_policies_attributes][0][purchase_price]': '5',
            'product[product_units_attributes][0][price_policies_attributes][0][_destroy]': 'false',
            'product[product_units_attributes][0][price_policies_attributes][0][document_type]': 'purchase',
            'product[product_units_attributes][0][price_policies_attributes][1][unit_id]': '117200',
            'product[product_units_attributes][0][price_policies_attributes][1][unit_name]': '包',
            'product[product_units_attributes][0][price_policies_attributes][1][sale_price]': '8',
            'product[product_units_attributes][0][price_policies_attributes][1][purchase_price]': '',
            'product[product_units_attributes][0][price_policies_attributes][1][_destroy]': 'false',
            'product[product_units_attributes][0][price_policies_attributes][1][document_type]': 'sale',
            'product[product_customer_types_attributes][0][name]': '一级代理商',
            'product[product_customer_types_attributes][0][customer_type_id]': '107688',
            'product[product_customer_types_attributes][0][default_percentage]': '100.0',
            'product[product_customer_types_attributes][1][name]': '二级代理商',
            'product[product_customer_types_attributes][1][customer_type_id]': '107689',
            'product[product_customer_types_attributes][1][default_percentage]': '100.0',
            'product[product_customer_types_attributes][2][name]': '普通客户',
            'product[product_customer_types_attributes][2][customer_type_id]': '107690',
            'product[product_customer_types_attributes][2][default_percentage]': '100.0',
            'product[product_customer_types_attributes][3][name]': '大客户',
            'product[product_customer_types_attributes][3][customer_type_id]': '107691',
            'product[product_customer_types_attributes][3][default_percentage]': '100.0',
            'product[product_customer_types_attributes][4][name]': '批发客户',
            'product[product_customer_types_attributes][4][customer_type_id]': '107692',
            'product[product_customer_types_attributes][4][default_percentage]': '100.0',
            'product[product_attr_groups_attributes][0][category]': 'default_attr',
            'product[product_attr_groups_attributes][0][product_attr_names]': '',
            'product[product_attr_groups_attributes][0][product_attr_ids]': '',
            'product[product_attr_groups_attributes][0][number]': '',
            'product[product_images_attributes][0][fileID]': 'o_1clbr9ucotr04kogl06bh1hs27',
            'product[product_images_attributes][0][filename]': 'lAHPBY0V40IDOmfM28zb_219_219.gif',
            'product[product_images_attributes][0][url]': 'https://obbsip92b.qnssl.com/FmzjkW3DieyLz6dzs7byB0R9lDr0?&e=1534778403&token=w2yRBQw0CPY-fsy6hxBjASopjHCTtT7RKFRtQeJz:8GIYW4aN1ZxPneVG5Qx5ccwxzPU='

        }
        #等待1秒，方便加载以下的产品data
        time.sleep(1)

        #属性产品的data
        self.attribute_data = {
            'product[number]': 'CP' + time.strftime("%H:%M:%S"),
            'product[name]': 'iPhone属性接口测试' + time.strftime("%H:%M:%S"),
            'product[barcode]': '条码'+ time.strftime("%H:%M:%S"),
            'product[product_category_id]': '150530',
            'product[spec]': 'iPhone的规格',
            'product[note]': 'iPhone的备注',
            'product[unit_id]': '117202',
            'product[standard_price]': '1',
            'product[default_unit_id]': '117202',
            'product[default_in_unit_id]': '117202',
            'product[current_warning_policy]': 'no_warning',
            'product[split_warning_status]': 'split_closed',
            'product[total_warning_status]': 'total_closed',
            'product[attr_warning_status]': 'attr_warning_closed',
            'product[attr_status]': 'attr_opened',
            'product[price_policy_setting]': 'product_attr_policy',
            'product[unit_setting]': 'single_unit',
            'product[batch_status]': 'batch_closed',
            'product[serial_code_status]': 'serial_closed',
            'product[life_warning_days]': '',
            'product[life_period]': '',
            'product[use_purchase_attribute]': 'true',
            'product[use_sale_attribute]': 'true',
            'product[use_customer_setting]': 'false',
            'product[use_customer_price]': 'false',
            'product[product_units][0][unit_id]': '117202',
            'product[product_units][0][unit_name]': '部',
            'product[product_customer_types][0][name]': '一级代理商',
            'product[product_customer_types][0][customer_type_id]': '107688',
            'product[product_customer_types][0][default_percentage]': '100.0',
            'product[product_customer_types][1][name]': '二级代理商',
            'product[product_customer_types][1][customer_type_id]': '107689',
            'product[product_customer_types][1][default_percentage]': '100.0',
            'product[product_customer_types][2][name]': '普通客户',
            'product[product_customer_types][2][customer_type_id]': '107690',
            'product[product_customer_types][2][default_percentage]': '100.0',
            'product[product_customer_types][3][name]': '大客户',
            'product[product_customer_types][3][customer_type_id]': '107691',
            'product[product_customer_types][3][default_percentage]': '100.0',
            'product[product_customer_types][4][name]': '批发客户',
            'product[product_customer_types][4][customer_type_id]': '107692',
            'product[product_customer_types][4][default_percentage]': '100.0',
            'product[text_field_74688f78d7]': '苹果官方旗舰店',
            'product[text_field_7776164791]': '高',
            'product[product_units_attributes][0][unit_id]': '117202',
            'product[product_units_attributes][0][unit_name]': '部',
            'product[product_customer_types_attributes][0][name]': '一级代理商',
            'product[product_customer_types_attributes][0][customer_type_id]': '107688',
            'product[product_customer_types_attributes][0][default_percentage]': '100.0',
            'product[product_customer_types_attributes][1][name]': '二级代理商',
            'product[product_customer_types_attributes][1][customer_type_id]': '107689',
            'product[product_customer_types_attributes][1][default_percentage]': '100.0',
            'product[product_customer_types_attributes][2][name]': '普通客户',
            'product[product_customer_types_attributes][2][customer_type_id]': '107690',
            'product[product_customer_types_attributes][2][default_percentage]': '100.0',
            'product[product_customer_types_attributes][3][name]': '大客户',
            'product[product_customer_types_attributes][3][customer_type_id]': '107691',
            'product[product_customer_types_attributes][3][default_percentage]': '100.0',
            'product[product_customer_types_attributes][4][name]': '批发客户',
            'product[product_customer_types_attributes][4][customer_type_id]': '107692',
            'product[product_customer_types_attributes][4][default_percentage]': '100.0',
            'product[product_attr_groups_attributes][0][category]': 'default_attr',
            'product[product_attr_groups_attributes][0][product_attr_names]': '',
            'product[product_attr_groups_attributes][0][product_attr_ids]': '',
            'product[product_attr_groups_attributes][0][number]': '',
            'product[product_attr_groups_attributes][1][category]': 'custom_attr',
            'product[product_attr_groups_attributes][1][number]': 'CP0003_1',
            'product[product_attr_groups_attributes][1][product_attr_ids]': '90558/90561',
            'product[product_attr_groups_attributes][1][product_attr_names]': '深空灰/64G',
            'product[product_attr_groups_attributes][1][price_policies_attributes][0][product_attr_group_product_attr_ids]': '90558/90561',
            'product[product_attr_groups_attributes][1][price_policies_attributes][0][product_attr_group_product_attr_names]': '深空灰/64G',
            'product[product_attr_groups_attributes][1][price_policies_attributes][0][unit_id]': '117202',
            'product[product_attr_groups_attributes][1][price_policies_attributes][0][sale_price]': '',
            'product[product_attr_groups_attributes][1][price_policies_attributes][0][purchase_price]': '55',
            'product[product_attr_groups_attributes][1][price_policies_attributes][0][purchase]': '55',
            'product[product_attr_groups_attributes][1][price_policies_attributes][0][document_type]': 'purchase',
            'product[product_attr_groups_attributes][1][price_policies_attributes][1][product_attr_group_product_attr_ids]': '90558/90561',
            'product[product_attr_groups_attributes][1][price_policies_attributes][1][product_attr_group_product_attr_names]': '深空灰/64G',
            'product[product_attr_groups_attributes][1][price_policies_attributes][1][unit_id]': '117202',
            'product[product_attr_groups_attributes][1][price_policies_attributes][1][sale_price]': '77',
            'product[product_attr_groups_attributes][1][price_policies_attributes][1][purchase_price]': '',
            'product[product_attr_groups_attributes][1][price_policies_attributes][1][sale]': '77',
            'product[product_attr_groups_attributes][1][price_policies_attributes][1][document_type]': 'sale',
            'product[product_attr_groups_attributes][2][category]': 'custom_attr',
            'product[product_attr_groups_attributes][2][number]': 'CP0003_2',
            'product[product_attr_groups_attributes][2][product_attr_ids]': '90559/90562',
            'product[product_attr_groups_attributes][2][product_attr_names]': '玫瑰红/256G',
            'product[product_attr_groups_attributes][2][price_policies_attributes][0][product_attr_group_product_attr_ids]': '90559/90562',
            'product[product_attr_groups_attributes][2][price_policies_attributes][0][product_attr_group_product_attr_names]': '玫瑰红/256G',
            'product[product_attr_groups_attributes][2][price_policies_attributes][0][unit_id]': '117202',
            'product[product_attr_groups_attributes][2][price_policies_attributes][0][sale_price]': '',
            'product[product_attr_groups_attributes][2][price_policies_attributes][0][purchase_price]': '66',
            'product[product_attr_groups_attributes][2][price_policies_attributes][0][purchase]': '66',
            'product[product_attr_groups_attributes][2][price_policies_attributes][0][document_type]': 'purchase',
            'product[product_attr_groups_attributes][2][price_policies_attributes][1][product_attr_group_product_attr_ids]': '90559/90562',
            'product[product_attr_groups_attributes][2][price_policies_attributes][1][product_attr_group_product_attr_names]': '玫瑰红/256G',
            'product[product_attr_groups_attributes][2][price_policies_attributes][1][unit_id]': '117202',
            'product[product_attr_groups_attributes][2][price_policies_attributes][1][sale_price]': '88',
            'product[product_attr_groups_attributes][2][price_policies_attributes][1][purchase_price]': '',
            'product[product_attr_groups_attributes][2][price_policies_attributes][1][sale]': '88',
            'product[product_attr_groups_attributes][2][price_policies_attributes][1][document_type]': 'sale',
            'product[product_attrables_attributes][0][product_attr_id]': '90556',
            'product[product_attrables_attributes][0][product_id]': '',
            'product[product_attrables_attributes][1][product_attr_id]': '90557',
            'product[product_attrables_attributes][1][product_id]': '',
            'product[product_images_attributes][0][fileID]': 'o_1clbs5dj21gk2dib427pha11767',
            'product[product_images_attributes][0][filename]': 'u=2572528570,3179480776&fm=58&w=121&h=140&img.JPEG',
            'product[product_images_attributes][0][url]': 'https://obbsip92b.qnssl.com/FucsDun_tumBUfcQbTY6gHlgxvia?&e=1534779303&token=w2yRBQw0CPY-fsy6hxBjASopjHCTtT7RKFRtQeJz:Kw0Pz0I7rVgzqsQLwotrsFTHRrs='
        }

    def add_product(self, data):
        headers = self.headers()
        # headers = self.add_authorization_token(headers)
        headers = self.all_headers(headers)
        r2 = self.session.post(self.base_url + '/api/products.json', data=data, headers=headers)
        print('新增产品：', r2.text)
        #self.session.close()


    # def custom_headers(self):
    #     headers = {
    #         "Upgrade-Insecure-Requests": "1",
    #         'Content-Type': 'application/x-www-form-urlencoded; charset=UTF-8',
    #         'Origin': self.base_url,
    #         'Connection': 'keep-alive',
    #     }
    #     return headers

if __name__ == '__main__':
    login = Login()
    login.user_login("13052371903", "111111")
    cookie = login.cookie
    newpro = NewProduct(cookie)
    newpro.add_product(newpro.attribute_data)
